# Render deployment configuration
# This file can be used to configure your Render service

# Service configuration for render.yaml (optional)
# You can use this for Infrastructure as Code deployment

services:
  - type: web
    name: modern360-assessment
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false

databases:
  - name: modern360-db
    plan: free
